### ISSUE TITLE
Sage 10 support

### ISSUE THREAD

**Issue by campaignupgrade** [FlorianMoser/bedrock-deployer#4]
The readme says Sage 9.0.* is supported, but will this work with Sage 10?

**Comment by FlorianMoser** [comment]
The Sage recipes only provide three tasks:

1. Run `composer install`
2. Compile the theme (nothing has changed here between 9 and 10)
3. Push the local /dist folder to the server

Sage 10 uses the /public folder for compiled assets, instead of the /dist folder. So you could simply omit calls to the tasks `sage:clear_assets`, `sage:upload_assets_only`, `sage:upload_assets` and `push:assets` and use it with Sage 10.

I would currently suggest to commit compiled assets to your Git repo anyway. This leads to more consistent deployments and you wouldn't need to compile and upload on every deployment.

Also, it is quite dangerous to wipe the assets directory on the server, it may contain data that should not be deleted. I tend towards removing the tasks mentioned above. Let me know what you think.

**Comment by campaignupgrade** [comment]
Thanks for the reply! I suspected that not much has changed between Sage 9 and 10. 

I'm hesitant to commit compiled code the the project repo. Some are philosophical, but some are practical; it makes it harder to search through a project when search includes code you'll never touch (and which duplicates the code you will touch). 

I've considered creating build repos *just* to handle the build artifacts, but this introduces the management headaches in creating and maintaining one repo per branch (dev, stage, production) or maybe one repo with three branches, but even the later is still yet another repo to manage.

A third option is to build local (or in a ci/cd service) and use git on the remote server. WP Engine deploys are pushed to a git repo, and SpinUpWP also supports git. Git on the remote seems increasingly available. We currently do this with our Sage 9 > CircleCI > WP Engine deploy process. 

That said I don't know which of the above options will prevail yet! More that just trying to solve my problem, I'm also looking to define a better framework for how WP CI/CD should work in the long term for all of us in an easy and modular system.

**Comment by campaignupgrade** [comment]
> I would currently suggest to commit compiled assets to your Git repo anyway. This leads to more consistent deployments and you wouldn't need to compile and upload on every deployment.

I'm not fond of building local in a multi-dev project. Too many variable. We've normalized most of those variables by using Lando for local dev, so all devs uses the same Lando containers, but there's still potential issues. 

Also as we expand our devops process we want to add a ton of testing and visual regression steps. This is pretty taxing on a local box, so we're currently looking at using GitHub actions to checkout the project, spin up Lando, do the build, runs the tests, and if it passes deploy to remote.

I'm also looking at how parts of this workflow Lando (vs Local or Docker Composer etc) and GitHub Actions (vs CircleCi, Perkins, Gitlab, etc) and all the testing could be easily swappable.

This approach would go a long ways towards making the CI?CD process repeatable, consistent, scalable, and modular... which would be a boon to the WordPress community. 

Your thoughts on this would be appreciated!

**Comment by FlorianMoser** [comment]
Thank you for sharing your deployment ideas, they sound very sophisticated.

I've spent days myself, figuring out an easy way to deploy Bedrock projects. Especially because I needed them to work on shared host (chroot) environments. But think about this: you take days to figure out the perfect build and deploy process, you engineer the best deployment code and you choose sophisticated web services to track, compile and deploy code.

Code for what? In 95% of the cases to make the server send plain text HTML code to a Browser. That's why I'm currently moving away from WordPress and use flatfile CMS or SSG more and more often. That reduces deployment pretty much down to a `git pull` on the server and saves a lot of time and costs.

That's why I probably won't make huge changes to this repo. But I'll try to maintain it as good as possible.

I think about making these changes:
- add a variable for the distribution files (so you can use /dist on Sage 9 and /public on Sage 10)
- add a warning comment to the recipes that compile/erase/upload Sage distribution files
- remove the compile/upload recipe from the example deployment recipe

**Comment by campaignupgrade** [comment]
Thanks for the update. I wondered why you'd been posting less often on Sage related content. I have a lot of frustrations with WP, but we're still years away from moving to a new CMS (and I am not sure if our kind of complex projects would fit another CMS). 

I like your idea of a variables for distribution folders. I also think about supporting non-Sage or non-Bedrock development, as well as your need to deploy to shared hosting. Which is how I got to the modular thinking; rather than one big deployer recipe that supports all possible use cases, something more like a core framework and independent sub-recipes might work — one person could write a Sage 10 module, someone else a "push to share hosting via ssh" module, yet another person a "Push via Git to WP Engine," and so on. This would require some sort of community organizing, I suspect. 

This is how I came to discover and why I'm evaluating it as a core tool. But, it also seems like Deployer out-of-the-box wants to run composer (and other processes?) on the remote host. I'm not fond of that idea — two issues are composer version control on the remote, and the inability to support deploy to shared hosting. I would rather it run local in Lando, and then run "local" in Lando in a CI/CD container like Github Actions, for tighter build control and hosting flexibility. 

I'm still only 85% sure deployer is going to work for us... but if it does I'd be happy to look at forking your project and making pull requests to update it.

**Comment by tobinski** [comment]
Currently deployer executes composer on the server to install all php dependencies. You could change the recipe to execute composer locally, as we do for all the node stuff and finally push all the assets to the remote. I experimented with a CI/CD setup, but moved away from it. It took too long to build, was very error prone and in the end slowed down my dev process.

**Comment by campaignupgrade** [comment]
I hear you there! We've built CI/CD in CircleCI, and then GitHub Actions, and now researching Deployer... it's a huge time sink. But we really need to add visual regression and have the client check off on it and regular building and testing locally is an even bigger pain.

**Comment by tobinski** [comment]
Some short overview about my experiment, maybe this is useful for you. I use gitlab as a dev platform. Devs uses feature branches to make changes to a protected main branch. If a feature was complete and the dev wanted to show it to the client. He  had to make a git tag. The tag triggered gitlab ci to build the project and deploy it to a stage environment. I used this depoyer recipe to do this task. Then we collected feedback from our clients.

If I have to do this again, I would use the features now backed into gitlab, like [deployments](https://docs.gitlab.com/ee/ci/environments/)

**Comment by campaignupgrade** [comment]
Am I reading this right, the container that holds the build can also host the dev/staging website? If so that's brilliant! 

The way I want to design CI/CD would also support that. Basically I put Lando in the deploy system because I got tired of maintaining parity between the development, deployment, and production systems. With Lando, dev and deploy are both run in the exact same Lando containerized system. Apache/Nginx, PHP versioning, MySQL/MariaDB versioning, all tooling like yarn and composer versions, are all spec'ed in Lando, so there's no need beyond the most basic deploy container config — any node container can run Lando. 

I also became frustrated at the lack of portability — whatever complex deploy I build on CircleCI could not be easily moved to GitHub Actions or GitLab Deployments. By using Deployer in Lando I am hoping to make the system portable across CI providers. I could conceivably use that on Gitlab's deploy-host combo. 

Ultimately I hope to be containerized all the way through to production... that would be a dream! But Lando is not for production containerization and I don't want to learn raw docker compose.

**Comment by tobinski** [comment]
This is off topic, but yes you can make the build (install composer/nodejs, build assets) and then automatically deploy the container. It may be better to use an extra build `stage` to build the assets and then use the wordpress image to deploy the container. Gitlab helps you with that and allows you to have preview deploys for branches and or tags. But this comes at costs. You need to have a Kubernetes cluster to use those fancy features. You now get managed ones (f.e. Digitalocean), quite cheap, but you still need to maintain it somehow. And you need to find a way to deal with the database.

**Comment by tobinski** [comment]
Back to the topic. I use bedrock-depoyer with sage 10, this works. Bedrock-deployer doesn't mess with sage directly. It solves a different problem. It solves the problem to deploy bedrock with deployer to shared hosted environments. I will open a pull request to clarify the readme

Btw. Between the internals of sage 9 and sage 10 things changed quite allot.

**Comment by FlorianMoser** [comment]
Feel free to continue your discussion. I closed the issue because the Sage 10 issue is fixed.

**Comment by campaignupgrade** [comment]
Apologies for this all going off-topic, @FlorianMoser. I hope you don't mind. It's hard to find quality discussion on WP CI/CD strategies. 

Would either of you be willing to share a Sage 9/10 deployer.php file so I can review your strategy? 

I'm also happy to take this offline at scott@campaignupgrade.org.

**Comment by FlorianMoser** [comment]
> Apologies for this all going off-topic, @FlorianMoser. I hope you don't mind. It's hard to find quality discussion on WP CI/CD strategies.

No problem at all.

> Would either of you be willing to share a Sage 9/10 deployer.php file so I can review your strategy?

I'm using pretty much exactly the [example recipe](https://github.com/FlorianMoser/bedrock-deployer/blob/master/examples/deploy.full-example.php) from the repo. Mostly paired with the [Plesk Deployer](https://github.com/FlorianMoser/plesk-deployer) to deploy to chroot environments. Everything in a project is stored in the repo, but stuff that cannot be executed on the (shared hosting) server (node js stuff like compiling).

On updates I:

1. make the changes to the code
2. test it
3. commit/push it
4. run `dep deploy` which:
5. create a new release folder on the server
6. checks out the updated repo
7. runs `composer install`
8. locally compiles Sage assets
9. uploads the compiled files to the server
10. activates the new release (switch to new release folder if previous steps were successful)

It's actually a pretty simplified process. @tobinski has more experience with containers.

*edit: fixed MD links
